{
    "config": {
        "error": {
            "bad_station_id": "L'ID d'estaci\u00f3 no \u00e9s v\u00e0lid, no est\u00e0 present o no es troba a la base de dades d'IDs d'estacions",
            "cannot_connect": "Ha fallat la connexi\u00f3",
            "unknown": "Error inesperat"
        },
        "step": {
            "user": {
                "data": {
                    "language": "Idioma de la informaci\u00f3 meteorol\u00f2gica",
                    "latitude": "Latitud",
                    "longitude": "Longitud",
                    "station": "ID de l'estaci\u00f3 meteorol\u00f2gica"
                }
            }
        }
    }
}