{
    "config": {
        "error": {
            "cannot_connect": "Nie uda\u0142o si\u0119 po\u0142\u0105czy\u0107"
        },
        "step": {
            "user": {
                "data": {
                    "password": "Has\u0142o",
                    "username": "Nazwa u\u017cytkownika"
                }
            }
        }
    }
}